### ISSUE TITLE
IPAddress problems

### ISSUE THREAD

**Issue by Yttrit** [ARCCN/runos#6]
We have IP Packet& pkt. Destination IP is 10.0.0.2, for example. Then if you write 
LOG(INFO) << pkt.load(oxm::ipv4_dst());
LOG(INFO) << AppObject::uint32_t_ip_to_string(pkt.load(oxm::ipv4_dst()));
you get 
>167772162
>2.0.0.10
and 10.0.0.2 != 2.0.0.10.
But if you write 
LOG(INFO) << IPAddress("10.0.0.2").getIPv4();
you get 
> 33554442
which doesn't equal to pkt.load(oxm::ipv4_dst())

**Comment by dShvetsov** [comment]
Hello.
The clue of this problem is confusion in big and little endian.
In net ip addresses are recorded in big endian.
pkt.load() converts value in little endian, but IPAddress().getIPv4() doesn't.
AppObject::uint32_t_ip_to_string also take unconverted value (in big endian).

167 772 162 = 0xA000002, when 33 554 442 = 0x200000A.

Thank you, for your report. We will aim to standardize this stuff.

**Comment by dShvetsov** [comment]
closed in f1e2ce8, by adding IPv4 address wrapper
